import type { Metadata } from "next";

import NavBar from "@/components/ui/NavBar";

import './globals.user.css'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootUserLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <NavBar />
            <main className="min-h-screen py-14 container mx-auto">
                {children}
            </main>
        </>
    );
}
